INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(100,'TOOTHPASTE');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(101,'BEAUTY');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(102,'KITCHEN');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(103,'BAKERY');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(104,'STATIONERY');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(105,'BABY PRODUCTS');