CREATE TABLE PRDCT_CTGRY(
  CTGRY_ID INT AUTO_INCREMENT PRIMARY KEY,
  CTGRY_DESC VARCHAR(30)
);

INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(100,'TOOTHPASTE');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(101,'BEAUTY');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(102,'KITCHEN');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(103,'BAKERY');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(104,'STATIONERY');
INSERT INTO PRDCT_CTGRY(CTGRY_ID,CTGRY_DESC) VALUES(105,'BABY PRODUCTS');

COMMIT;

CREATE TABLE PRDCTS (
   PRDCT_ID INT AUTO_INCREMENT PRIMARY KEY,
   PRDCT_NM VARCHAR(30),
   PRDCT_DESC VARCHAR(30),
   PRDCT_HSN VARCHAR(20),
   PRDCT_PRCE DECIMAL(10,2),
   CTGRY_ID INT,
   FOREIGN KEY(CTGRY_ID) REFERENCES PRDCT_CTGRY(CTGRY_ID)
);